--- 
# Create a volume for the registry
- hosts: localhost
  vars:
    osp_volumes:
    - name: "{{ env_id }}.{{ dns_domain }}-registry"
      display_description: "Registry Vol"
      display_name: "{{ env_id }}.{{ dns_domain }}-registry"
      size: "{{ casl_registry_size | default(20) }}"
      purpose: "ose_registry"
  roles: 
  - infra-ansible/roles/osp/admin-volume

- hosts: OSEv3
  tasks:
  - name: "set registry fact"
    set_fact: 
      openshift_hosted_registry_storage_kind: openstack
      openshift_hosted_registry_storage_openstack_volumeID: "{{ disk.volume.id }}"
      openshift_hosted_registry_storage_volume_size: "{{ disk.volume.size }}Gi"
      openshift_hosted_registry_storage_access_modes: ['ReadWriteOnce']
      openshift_hosted_registry_storage_openstack_filesystem: ext4
    with_items: 
    -  "{{ hostvars['localhost'].os_volumes.results }}"
    when: 
    - disk.item.purpose  == "ose_registry"
    loop_control:
      loop_var: disk

